-- Views for table joins and generating results --

-- Use class_ID and FACULTY_ID in where clause to 
-- select the required records

CREATE VIEW CLASS_STUDENTS AS 
SELECT S.STUDENT_ID, S.NAME, S.ROLLNO, S.MAJOR, S.YEAR, S.DOB, S.EMAIL, C.CLASS_ID, C.FACULTY_ID
FROM STUDENT S
INNER JOIN BELONGSTO B ON S.STUDENT_ID=B.STUDENT_ID
INNER JOIN CLASS C ON B.CLASS_ID=C.CLASS_ID;

CREATE VIEW CLASS_LECTURES AS
SELECT C.FACULTY_ID, C.CLASS_ID, L.LECTURE_ID, L.DURATION, L.START_TIME, L.THRESHOLD_PERCENT
FROM CLASS C
INNER JOIN LECTURE L ON C.CLASS_ID=L.CLASS_ID;

CREATE VIEW STUDENT_ATTENDANCE AS
SELECT S.STUDENT_ID, S.ROLLNO, S.NAME, S.EMAIL, A.ISPRESENT, L.START_TIME, L.LECTURE_ID, L.CLASS_ID, L.FACULTY_ID
FROM STUDENT S
INNER JOIN ATTENDS A ON S.STUDENT_ID=A.STUDENT_ID
INNER JOIN CLASS_LECTURES L ON A.LECTURE_ID=L.LECTURE_ID;
